### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3342: character maps to <undefined>

### ISSUE THREAD

**Issue by gniadoo** [pypa/sampleproject#176]
Hi!
I am using Windows 11 and python 3.10.7 and i have a blocker just at the beginning when i try to install lib using cmd `python -m pip install -U algorithmlib --no-cache-dir` and i get traceback like below:
```
Collecting algorithmlib
  Downloading AlgorithmLib-3.3.8.tar.gz (14.9 MB)
     ---------------------------------------- 14.9/14.9 MB 36.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\gniad\AppData\Local\Temp\pip-install-pw8s5dhf\algorithmlib_7b21ec7796154a698f0e198fa0dad273\setup.py", line 6, in <module>
          long_description = fh.read()
        File "C:\Users\gniad\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3342: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Do you know possible workaround for this problem? Or is it even possible to run this project on Windows?

**Comment by dmtucker** [comment]
@gniadoo You should email majianli@corp.netease.com and tell them to update the project URL for `algorithmlib` (which has nothing to do with `sampleproject`).
